### ISSUE TITLE
修复 点击放大 出现页面溢出的问题

### ISSUE THREAD

**Issue by xQuotes** [CoinLQ/TripitakaPlatform#312]
https://github.com/CoinLQ/TripitakaPlatform/blob/36fca88e7176292586a3868aabfd15b6408e334b/static/custom/css/style.css#L786
```
.correct-in {
 margin: 15px;
 width: 100%;
}
```

**Comment by lvpython** [comment]
已加入到最新的commit中。感恩 @xQuotes
